In [97]:
import pandas as pd

In [98]:

main=pd.read_csv('realistic_lca_metals_dataset.csv')

In [99]:
main.sample(2)

,Process_Type,Metal,Energy_MJ_per_kg,Quantity_kg,Energy_MJ_total,Transport_km,Transport_Mode,Transport_emissions_kgCO2,Water_use_m3_per_ton,End_of_Life,Circularity_option,Process_emissions_kgCO2,Total_emissions_kgCO2,Emission_factor_kgCO2_per_MJ
77,Secondary,Aluminium,15.43,2000,30862.52,1187.0,Ship,47.48,1.102,Landfill,NaN,25212.91,25260.39,0.817
79,Primary,Aluminium,NaN,1000,203723.31,NaN,Train,0.63,NaN,Landfill,NaN,518485.33,518485.96,2.545

In [100]:
import tensorflow as tf
from tensorflow.keras import layers,Model

In [101]:
class LCAmodel(Model):
    def __init__(self,input_dim=14,hidden_dim=32):
        super(LCAmodel, self).__init__()
       

        self.encoder=tf.keras.Sequential([
            layers.Dense(hidden_dim,activation='relu'),
            layers.Dense(hidden_dim,activation='relu')
        ])

        self.decoder=tf.keras.Sequential([
            layers.Dense(input_dim)
        ])

    def call(self,inputs):
        x,mask=inputs
        inp=tf.concat([x,mask],axis=1)
        print(inp.shape)
        h=self.encoder(inp)
        out=self.decoder(h)
        return out

    def compile(self,optimizer,loss):
        self.encoder.compile(optimizer=optimizer,loss=loss)
        self.decoder.compile(optimizer=optimizer,loss=loss)

In [94]:
x = tf.constant([[100, 1, 0, 200, 50, 0, 0, 80, 10, 1, 1, 200, 500, 0]], dtype=tf.float32)
mask = tf.constant([[1,1,0,1,1,0,0,1,1,1,1,1,1,0]], dtype=tf.float32)

y_true = tf.constant([[100, 1, 300, 200, 50, 75, 60, 80, 10, 1, 1, 200, 500, 20]], dtype=tf.float32)

In [16]:
main['Process_Type'].value_counts()

Process_Type
Primary      153
Secondary     47
Name: count, dtype: int64

In [17]:
main['Metal'].value_counts()

Metal
Aluminium    90
Steel        60
Copper       50
Name: count, dtype: int64

In [18]:
main['Transport_Mode'].value_counts()

Transport_Mode
Truck    120
Train     47
Ship      33
Name: count, dtype: int64

In [19]:
main['End_of_Life'].value_counts()

End_of_Life
Recycle     102
Landfill     63
Reuse        35
Name: count, dtype: int64

In [20]:
main['Circularity_option'].value_counts()

Circularity_option
Closed-loop    98
Open-loop      39
Name: count, dtype: int64

In [21]:
main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Process_Type                  200 non-null    object
 1   Metal                         200 non-null    object
 2   Energy_MJ_per_kg              184 non-null    float64
 3   Quantity_kg                   200 non-null    int64
 4   Energy_MJ_total               200 non-null    float64
 5   Transport_km                  184 non-null    float64
 6   Transport_Mode                200 non-null    object
 7   Transport_emissions_kgCO2     200 non-null    float64
 8   Water_use_m3_per_ton          184 non-null    float64
 9   End_of_Life                   200 non-null    object
 10  Circularity_option            137 non-null    object
 11  Process_emissions_kgCO2       200 non-null    float64
 12  Total_emissions_kgCO2         200 non-null    float64
 13  Emission_factor_kgCO2_per_MJ  200 non-null    float64
dtypes: float64(8), int64(1), object(5)
memory usage: 22.0+ KB

In [49]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [50]:
main['Process_Type']=le.fit_transform(main['Process_Type'])
main['Metal']=le.fit_transform(main['Metal'])
main['End_of_Life']=le.fit_transform(main['End_of_Life'])
main['Circularity_option']=le.fit_transform(main['Circularity_option'])
main['Transport_Mode']=le.fit_transform(main['Transport_Mode'])

In [51]:
main

,Process_Type,Metal,Energy_MJ_per_kg,Quantity_kg,Energy_MJ_total,Transport_km,Transport_Mode,Transport_emissions_kgCO2,Water_use_m3_per_ton,End_of_Life,Circularity_option,Process_emissions_kgCO2,Total_emissions_kgCO2,Emission_factor_kgCO2_per_MJ
0,0,0,189.22,100,18922.33,1072.0,0,2.14,5.787,1,0,54747.46,54749.61,2.893
1,0,2,349.51,500,174753.56,504.0,2,30.24,10.029,0,2,548031.47,548061.71,3.136
2,0,2,319.62,100,31961.97,436.0,0,0.87,7.797,2,0,102041.61,102042.48,3.193
3,0,1,57.69,1000,57690.73,928.0,2,111.36,3.194,1,1,74605.21,74716.57,1.293
4,0,0,207.79,100,20779.02,NaN,2,1.92,7.533,1,0,57503.28,57505.20,2.767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0,0,167.02,100,16701.79,82.0,2,0.98,6.440,1,0,44249.45,44250.44,2.649
196,1,2,69.79,2000,139575.34,NaN,0,26.28,2.354,1,1,160338.59,160364.87,1.149
197,0,2,308.72,1000,308718.43,1103.0,0,22.06,7.464,1,1,1095636.43,1095658.49,3.549
198,0,2,333.00,250,83251.01,434.0,2,13.02,8.881,0,2,327896.97,327909.99,3.939
199,0,2,298.60,250,74649.58,1008.0,0,5.04,7.169,1,0,218218.39,218223.43,2.923

In [52]:
from sklearn.impute import SimpleImputer

In [53]:
imputer = SimpleImputer(strategy='mean')

In [54]:
imputed_data = imputer.fit_transform(main)

In [55]:
main.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 14 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   Process_Type                  200 non-null    int64
 1   Metal                         200 non-null    int64
 2   Energy_MJ_per_kg              184 non-null    float64
 3   Quantity_kg                   200 non-null    int64
 4   Energy_MJ_total               200 non-null    float64
 5   Transport_km                  184 non-null    float64
 6   Transport_Mode                200 non-null    int64
 7   Transport_emissions_kgCO2     200 non-null    float64
 8   Water_use_m3_per_ton          184 non-null    float64
 9   End_of_Life                   200 non-null    int64
 10  Circularity_option            200 non-null    int64
 11  Process_emissions_kgCO2       200 non-null    float64
 12  Total_emissions_kgCO2         200 non-null    float64
 13  Emission_factor_kgCO2_per_MJ  200 non-null    float64
dtypes: float64(8), int64(6)
memory usage: 22.0 KB

In [58]:
imputed_data=pd.DataFrame(imputed_data)

In [61]:
imputed_data.columns=main.columns

In [62]:
imputed_data

,Process_Type,Metal,Energy_MJ_per_kg,Quantity_kg,Energy_MJ_total,Transport_km,Transport_Mode,Transport_emissions_kgCO2,Water_use_m3_per_ton,End_of_Life,Circularity_option,Process_emissions_kgCO2,Total_emissions_kgCO2,Emission_factor_kgCO2_per_MJ
0,0.0,0.0,189.22,100.0,18922.33,1072.00000,0.0,2.14,5.787,1.0,0.0,54747.46,54749.61,2.893
1,0.0,2.0,349.51,500.0,174753.56,504.00000,2.0,30.24,10.029,0.0,2.0,548031.47,548061.71,3.136
2,0.0,2.0,319.62,100.0,31961.97,436.00000,0.0,0.87,7.797,2.0,0.0,102041.61,102042.48,3.193
3,0.0,1.0,57.69,1000.0,57690.73,928.00000,2.0,111.36,3.194,1.0,1.0,74605.21,74716.57,1.293
4,0.0,0.0,207.79,100.0,20779.02,685.86413,2.0,1.92,7.533,1.0,0.0,57503.28,57505.20,2.767
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
195,0.0,0.0,167.02,100.0,16701.79,82.00000,2.0,0.98,6.440,1.0,0.0,44249.45,44250.44,2.649
196,1.0,2.0,69.79,2000.0,139575.34,685.86413,0.0,26.28,2.354,1.0,1.0,160338.59,160364.87,1.149
197,0.0,2.0,308.72,1000.0,308718.43,1103.00000,0.0,22.06,7.464,1.0,1.0,1095636.43,1095658.49,3.549
198,0.0,2.0,333.00,250.0,83251.01,434.00000,2.0,13.02,8.881,0.0,2.0,327896.97,327909.99,3.939
199,0.0,2.0,298.60,250.0,74649.58,1008.00000,0.0,5.04,7.169,1.0,0.0,218218.39,218223.43,2.923

In [64]:
def datagenerator(arr):
    mask=np.random.choice([0,1],arr.shape)
    return mask

In [68]:
datagenerator(main.iloc[0])

array([1, 0, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0])

In [105]:
import time
for _ in range(8):
    print(_,end='\r')
    time.sleep(0.2)

7

In [95]:
model=LCAmodel()
model.compile(optimizer='adam',loss='mse')

In [96]:
optimizer = tf.keras.optimizers.Adam(learning_rate=0.01)

for epoch in range(500):
    for _ in range(10):
        with tf.GradientTape() as tape:
        y_pred = model((x, mask))
        loss = tf.reduce_mean(((y_pred - y_true)**2) * (1 - mask))
    grads = tape.gradient(loss, model.trainable_variables)
    optimizer.apply_gradients(zip(grads, model.trainable_variables))

y_pred = model((x, mask))
print("Input with missing:", x.numpy())
print("Mask:", mask.numpy())
print("Predicted full row:", y_pred.numpy())

(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
(1, 28)
Input with missing: [[100.   1.   0. 200.  50.   0.   0.  80.  10.   1.   1. 200. 500.   0.]]
Mask: [[1. 1. 0. 1. 1. 0. 0. 1. 1. 1. 1. 1. 1. 0.]]
Predicted full row: [[   1.3636569  145.59004    300.         -16.72352     -8.531496
    75.00002     60.00005    -38.742523  -150.62222     70.29143
  -111.81529    -27.51973    130.95384     20.000011 ]]

In [107]:
data=pd.read_excel('Converted_File.xlsx')

In [108]:
data

,Process_Type,Metal,Energy_MJ,Quantity_kg,Energy_Total_MJ,Transport_km,Transport_Mode,Water_use,End_of_Life
0,Secondary,Copper,27.39,1292,35394.08,829,Train,2.69,Recycle
1,Primary,Zinc,106.88,1434,153283.52,1184,Truck,7.8,Landfill
2,Primary,Aluminium,218.49,1526,333854.74,1381,Truck,5.32,Mixed
3,Secondary,Steel,35.43,892,31602.36,1087,Train,3.31,Recycle
4,Primary,Steel,366.19,252,92279.88,1031,Train,12.78,Recycle
...,...,...,...,...,...,...,...,...,...
3253,Secondary,Nickel,44.57,1100,49027.0,865,Ship,3.58,Recycle
3254,Primary,Nickel,304.82,200,60964.0,1024,Ship,9.18,Recycle
3255,Secondary,Aluminium,9.3,500,4650.0,526,Train,2.89,Landfill
3256,Secondary,Copper,20.19,1000,20190.0,1053,Train,2.0,Reuse
3257,Primary,Steel,343.89,1700,584613.0,NaN,NaN,NaN,NaN